# ============================================================
#  blocks.py — константи та налаштування блоків
# ============================================================

BLOCK_AIR = 0
BLOCK_DIRT = 1
BLOCK_GRASS = 2
BLOCK_HOUSE = 3
BLOCK_CAVE = 4
BLOCK_STONE = 5
BLOCK_WOOD_LOG = 6
BLOCK_WORKBENCH = 7
BLOCK_FURNACE = 8
BLOCK_CHEST = 9
BLOCK_LADDER = 10
BLOCK_DOOR = 11
BLOCK_COAL_ORE = 12
BLOCK_IRON_ORE = 13
BLOCK_GOLD_ORE = 14
BLOCK_TITANIUM_ORE = 15
BLOCK_COPPER_ORE = 16        
BLOCK_ARENA_WALL = 20
BLOCK_WATER = 21             
BLOCK_UNBREAKABLE_DIRT = 22  
BLOCK_ROCKET_PAD_LEFT = 23
BLOCK_ROCKET_PAD_CENTER = 24
BLOCK_ROCKET_PAD_RIGHT = 25

# --- НОВЕ: РАКЕТА (3х5) ---
BLOCK_ROCKET = 26
BLOCK_ROCKET_PART = 27
BLOCK_LAVA = 28
BLOCK_BREWING_STAND = 29
BLOCK_RARE_CHEST = 30
BLOCK_PLATFORM = 31

NON_SOLID_BLOCKS = {
    BLOCK_AIR, BLOCK_CAVE, BLOCK_HOUSE, BLOCK_LADDER, BLOCK_DOOR,
    BLOCK_WATER, BLOCK_ROCKET, BLOCK_ROCKET_PART, BLOCK_LAVA,
    BLOCK_WOOD_LOG, BLOCK_WORKBENCH, BLOCK_FURNACE, BLOCK_CHEST, BLOCK_BREWING_STAND,
    BLOCK_RARE_CHEST, BLOCK_PLATFORM
}
WORK_BLOCKS = {BLOCK_WORKBENCH, BLOCK_FURNACE, BLOCK_CHEST, BLOCK_BREWING_STAND, BLOCK_RARE_CHEST}

from src.core.data_loader import data_manager

BLOCK_DEFS = data_manager.blocks
